name: release

on:
    push:
      branches-ignore:
        - '**'
      tags:
        - 'v*'
  
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - run: zip -r GitHubActionSundbox.zip ./ -x "*.git*" "*output*" "*.gitignore*"
